### ISSUE TITLE
can not discover function

### ISSUE THREAD

**Issue by tentruycapcuaban** [KuroNeko-san/ponvif#1]
Hi can you help
i cant run function 
require 'class.ponvif.php';
$onvif = new Ponvif();
$result = $onvif->discover();
print_r($result);

error
![image](https://cloud.githubusercontent.com/assets/17898925/15732616/058a2276-28a9-11e6-9b42-125ba42af9a8.png)

if change 
![image](https://cloud.githubusercontent.com/assets/17898925/15732634/207e3f36-28a9-11e6-8c1f-29914bf1f485.png)
 it show 
![image](https://cloud.githubusercontent.com/assets/17898925/15732652/3b75b1ac-28a9-11e6-82c2-fbfa684adf4a.png)

==> how to fix this problem

**Comment by KuroNeko-san** [comment]
Hello.
It seems to be windows-specific thing. I made some changes in discover(), can you try current version ?

**Comment by tentruycapcuaban** [comment]
tks for response
i had changed 
still error
![image](https://cloud.githubusercontent.com/assets/17898925/15766234/88335ee6-2966-11e6-8e67-25d24866f02a.png)
![image](https://cloud.githubusercontent.com/assets/17898925/15766249/b42ad0ec-2966-11e6-9367-2c07dc98d1af.png)
any solutions???

**Comment by KuroNeko-san** [comment]
1) Do not change library code - use properties wrappers
2) "192.168.1.5" is example, if you want use binding to defined network card, you have to define you own IP. On windows command is "ipconfig /all". **Win+R, cmd, OK, ipconfig /all**
This is optional function.
3) "Array()" is result. No one video transmitters was found.

**Comment by KuroNeko-san** [comment]
Problem still exists ?

**Comment by tentruycapcuaban** [comment]
not fix
tks





*Thanks and Best Regards!*
*       Phạm Xuân Sơn  *
*M: 091.4242.998 - 090.671.4411*

2016-06-06 21:58 GMT+07:00 KuroNeko-san <notifications@github.com>:

**Comment by tentruycapcuaban** [comment]
any solution

**Comment by KuroNeko-san** [comment]
What kind of error you getting now ?

**Comment by tentruycapcuaban** [comment]
​if you free​
can you fix it

$obCampaignPhonestock = ObCampaignPhonestock::find()
    ->joinWith('ob_phone_stock',true,'INNER JOIN')
    ->where(['=','ob_phone_stock.ID','ob_campaign_phonestock.phone_stock_id'])
    ->andwhere(['=', 'id_campaign', $this->ID])
    ->andWhere(['=', 'status', CodeMst::GROUP_PHONESTOCK_CALL_STATUS_AVAILABLE])
    ->andWhere(['IS', 'complete_date', null])

    ->orderBy('RAND() limit 100000'); // tung 16/12/2015 tang toc do
get customer random


where error ???

discover error, i will show later









*Thanks and Best Regards!*
*       Phạm Xuân Sơn  *
*M: 091.4242.998 - 090.671.4411*

2016-06-13 15:50 GMT+07:00 KuroNeko-san <notifications@github.com>:

**Comment by KuroNeko-san** [comment]
Sorry, but it is not connected with my code. Refer to your framework developers.
