### ISSUE TITLE
Using RTSP

### ISSUE THREAD

**Issue by yohanes-ai** [KuroNeko-san/ponvif#16]
As your example code 

```
<?php

require 'class.ponvif.php';

$onvif = new Ponvif();
$onvif->setUsername('admin');
$onvif->setPassword('password');
$onvif->setIPAddress('192.168.1.108');

// In some cases you need to set MediaUrl manually. You can find it in "XAddrs" key (see above).
// $onvif->setMediaUri('http://192.168.1.108:3388/onvif/device_service');

try
{
	$onvif->initialize();
	
	$sources = $onvif->getSources();
	$profileToken = $sources[0][0]['profiletoken'];
	$mediaUri = $onvif->media_GetStreamUri($profileToken);
	
	var_dump($mediaUri);
}
catch(Exception $e)
{
	
}
```

I Got RTSP string bellow
`string(86) "rtsp://xx.xx.xx.xx:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1"`

What should I do with this RTSP?

**Comment by KuroNeko-san** [comment]
You can get live video from target device using this RTSP-link (using VLC):
```
vlc -vvv "rtsp://xx.xx.xx.xx:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1"
```
or simply get media info about stream (using FFmpeg):
```
ffprobe -i "rtsp://xx.xx.xx.xx:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1"
```
or record stream to file (using FFmpeg):
```
ffmpeg -rtsp_transport tcp -i "rtsp://xx.xx.xx.xx:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1" -vcodec copy -preset ultrafast -analyzeduration 500000 -tune zerolatency -acodec aac -ar 44100 -ac 1 -f mp4 /path/to/file.mp4
```
or restream to RTMP server (broadcast to Youtube, or somewhere else) (using FFmpeg):
```
ffmpeg -rtsp_transport tcp -i "rtsp://xx.xx.xx.xx:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1" -vcodec copy -preset ultrafast -analyzeduration 500000 -tune zerolatency -acodec aac -ar 44100 -ac 1 -f flv "rtmp://host:1935/path"
```
or whatever you want.

**Comment by JhonImmanuel** [comment]
Hi. Thanks for your quick reply. However we want to display it on browser. Is it possible to stream using either PHP or Java Web servlet?

I've read from several site or community that there are no the best way to do this on browser. Is iy true?

**Comment by KuroNeko-san** [comment]
Most usable (and cross platform) way to play live video in a browser IMHO is HLS with RTMP fallback, but it uses flash player. And it needed media server, of course.

For my testing i build chain:

[IP camera] --RTSP--> [FFmpeg] --RTMP --> [Nginx  RTMP module] --HLS, RTMP--> [web flash player]

Other way - WebRTC, but i have not expirity in it.

**Comment by JhonImmanuel** [comment]
Is there any references? Or maybe some example for us? I

**Comment by KuroNeko-san** [comment]
Nginx RTMP module - https://github.com/arut/nginx-rtmp-module
Complete guide (by nginx module author) - https://habrahabr.ru/post/162237/ (Russian)
Flash player with HLS support - https://github.com/denivip/StrobeMediaPlayback
FFmpeg settings above - from real build, you can use it as is.

Linux skills required.

If extremely needed i can build virtual machine (OpenVZ or VMware) with compiled software, but it takes time.

**Comment by JhonImmanuel** [comment]
I think is it very tricky, isn't it? is there any simple method? I've read from many site and it is hard to do. Very upset regarding this. However, how any CCTV VMS can generally access cctv on browser?

**Comment by ezimerman** [comment]
You need a streaming server if you're using RTSP. If the camera supports RTMP, you can use Youtube to get an embed link to put into your webpage.

**Comment by KuroNeko-san** [comment]
All answers given.
