### ISSUE TITLE
Discovery returns only 1 endpoint in array

### ISSUE THREAD

**Issue by AcroManiac** [KuroNeko-san/ponvif#17]
Hello!

I have 5 Onvif IP-cameras in my network. They are detected with standard Onvif Device Manager and Onvifer mobile application. When I try to discover them with ponvif it returns only 1 element in response array. I set discovery timeout to 5 seconds but result is the same.

Please tell how to discover all the 5 cameras with one function call? 

artem@artem-inspirion:~/Projects/ponvif$ php ./test_discover.php 
Array
(
    [0] => Array
        (
            [EndpointReference] => Array
                (
                    [Address] => urn:uuid:74:73:36:01:99:73
                )

            [Types] => dn:NetworkVideoTransmitter
            [Scopes] => onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/hardware/MDC-N4090 onvif://www.onvif.org/location/Europe/Kaliningrad onvif://www.onvif.org/name/MDC-N4090
            [XAddrs] => http://192.168.1.61/onvif/device_service
            [MetadataVersion] => 1540978103
            [IPAddr] => 192.168.1.61
        )

)
 
artem@artem-inspirion:~/Projects/ponvif$ php ./test_discover.php 
Array
(
    [0] => Array
        (
            [EndpointReference] => Array
                (
                    [Address] => urn:uuid:00025000-0001-D001-5775-001323A00B67
                )

            [Types] => dn:NetworkVideoTransmitter
            [Scopes] => onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/name/IPN100HD-5110PIR-EU onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/location/ onvif://www.onvif.org/hardware/IPN100HD 
            [XAddrs] => http://192.168.1.103:80/onvif/device_service
            [MetadataVersion] => 144
            [IPAddr] => 192.168.1.103
        )

)

**Comment by mcmidget** [comment]
I have the same problem, only one endpoint is detected.

Just for the record ... 
There are 2 IP Cams currently in my LAN with IPs 192.168.1.69 and 192.168.1.70
If I launch 2 discoveries in a row, the first detects 192.168.1.70 and the second 192.168.1.69

**Comment by cycne** [comment]
I fixed in pull request #15  , but no accepted.
Check it out my fork.

**Comment by KuroNeko-san** [comment]
Fixed by @cycne
